### ISSUE TITLE
Separate into lines automatically?

### ISSUE THREAD

**Issue by torridgristle** [danocmx/node-tf2-static-schema#3]
Currently all contents of the schema are in one line which is awful for human readability and also doesn't play well with Github's diffs which work by line. As it stands, it shows me the entire contents for what changed, even if it's just one name, making it useless.

**Comment by danocmx** [comment]
The schema is not supposed to be readable for humans, it's meant to be smaller to be downloaded to your application. You can always prettify it with any code editor.
